import '../../../../foundation/colors.dart';
import '../../../component_themes/syntax_theme_data.dart';

/// White Theme implementation of [CarbonSyntaxThemeData].
class WhiteSyntaxThemeData extends CarbonSyntaxThemeData {
  const WhiteSyntaxThemeData()
      : super(
          syntaxComment: CarbonPalette.green60,
          syntaxLineComment: CarbonPalette.green60,
          syntaxBlockComment: CarbonPalette.green60,
          syntaxDocComment: CarbonPalette.green60,
          syntaxString: CarbonPalette.gray100,
          syntaxDocString: CarbonPalette.gray100,
          syntaxKeyword: CarbonPalette.blue60,
          syntaxOperatorKeyword: CarbonPalette.blue60,
          syntaxControlKeyword: CarbonPalette.purple70,
          syntaxDefinitionKeyword: CarbonPalette.cyan70,
          syntaxModuleKeyword: CarbonPalette.purple70,
          syntaxVariable: CarbonPalette.blue60,
          syntaxName: CarbonPalette.blue60,
          syntaxVariableName: CarbonPalette.blue60,
          syntaxLabelName: CarbonPalette.blue60,
          syntaxAttribute: CarbonPalette.cyan70,
          syntaxAttributeName: CarbonPalette.cyan70,
          syntaxPropertyName: CarbonPalette.cyan70,
          syntaxTag: CarbonPalette.teal60,
          syntaxTagName: CarbonPalette.teal60,
          syntaxType: CarbonPalette.teal60,
          syntaxTypeName: CarbonPalette.teal60,
          syntaxClassName: CarbonPalette.teal60,
          syntaxNamespace: CarbonPalette.teal60,
          syntaxMacroName: CarbonPalette.gray100,
          syntaxAtom: CarbonPalette.gray100,
          syntaxLiteral: CarbonPalette.gray100,
          syntaxBool: CarbonPalette.gray100,
          syntaxNull: CarbonPalette.gray100,
          syntaxSelf: CarbonPalette.teal60,
          syntaxNumber: CarbonPalette.green60,
          syntaxInteger: CarbonPalette.green60,
          syntaxFloat: CarbonPalette.green60,
          syntaxUnit: CarbonPalette.green60,
          syntaxCharacter: CarbonPalette.gray100,
          syntaxAttributeValue: CarbonPalette.gray100,
          syntaxSpecialString: CarbonPalette.purple60,
          syntaxRegexp: CarbonPalette.purple70,
          syntaxEscape: CarbonPalette.coolGray80,
          syntaxUrl: CarbonPalette.coolGray80,
          syntaxColor: CarbonPalette.gray100,
        );
}
