import 'package:flutter/material.dart';
import '../../../foundation/colors.dart';
import '../../component_themes/layer_theme_data.dart';

/// Gray 10 Theme implementation of [CarbonLayerThemeData].
class G10LayerThemeData extends CarbonLayerThemeData {
  const G10LayerThemeData()
    : super(
        background: CarbonPalette.gray10,
        backgroundInverse: CarbonPalette.gray80,
        backgroundBrand: CarbonPalette.blue60,
        backgroundActive: const Color(0x808D8D8D), // gray50 @ 0.5
        backgroundHover: const Color(0x1F8D8D8D), // gray50 @ 0.12
        backgroundInverseHover: CarbonPalette.gray80Hover,
        backgroundSelected: const Color(0x338D8D8D), // gray50 @ 0.2
        backgroundSelectedHover: const Color(0x528D8D8D), // gray50 @ 0.32
        layer01: CarbonPalette.white,
        layerActive01: CarbonPalette.gray30,
        layerBackground01: CarbonPalette.gray10,
        layerHover01: CarbonPalette.whiteHover,
        layerSelected01: CarbonPalette.gray20,
        layerSelectedHover01: CarbonPalette.gray20Hover,
        layer02: CarbonPalette.gray10,
        layerActive02: CarbonPalette.gray30,
        layerBackground02: CarbonPalette.white,
        layerHover02: CarbonPalette.gray10Hover,
        layerSelected02: CarbonPalette.gray20,
        layerSelectedHover02: CarbonPalette.gray20Hover,
        layer03: CarbonPalette.white,
        layerActive03: CarbonPalette.gray30,
        layerBackground03: CarbonPalette.gray10,
        layerHover03: CarbonPalette.whiteHover,
        layerSelected03: CarbonPalette.gray20,
        layerSelectedHover03: CarbonPalette.gray20Hover,
        layerSelectedInverse: CarbonPalette.gray100,
        layerSelectedDisabled: CarbonPalette.gray50,
        layerAccent01: CarbonPalette.gray20,
        layerAccentActive01: CarbonPalette.gray40,
        layerAccentHover01: CarbonPalette.gray20Hover,
        layerAccent02: CarbonPalette.gray20,
        layerAccentActive02: CarbonPalette.gray40,
        layerAccentHover02: CarbonPalette.gray20Hover,
        layerAccent03: CarbonPalette.gray20,
        layerAccentActive03: CarbonPalette.gray40,
        layerAccentHover03: CarbonPalette.gray20Hover,
        field01: CarbonPalette.white,
        fieldHover01: CarbonPalette.whiteHover,
        field02: CarbonPalette.gray10,
        fieldHover02: CarbonPalette.gray10Hover,
        field03: CarbonPalette.white,
        fieldHover03: CarbonPalette.whiteHover,
        borderSubtle00: CarbonPalette.gray30,
        borderSubtle01: CarbonPalette.gray20,
        borderSubtleSelected01: CarbonPalette.gray30,
        borderSubtle02: CarbonPalette.gray30,
        borderSubtleSelected02: CarbonPalette.gray30,
        borderSubtle03: CarbonPalette.gray20,
        borderSubtleSelected03: CarbonPalette.gray30,
        borderStrong01: CarbonPalette.gray50,
        borderStrong02: CarbonPalette.gray50,
        borderStrong03: CarbonPalette.gray50,
        borderTile01: CarbonPalette.gray40,
        borderTile02: CarbonPalette.gray30,
        borderTile03: CarbonPalette.gray40,
        borderInverse: CarbonPalette.gray100,
        borderInteractive: CarbonPalette.blue60,
        borderDisabled: CarbonPalette.gray30,
        focus: CarbonPalette.blue60,
        focusInset: CarbonPalette.white,
        focusInverse: CarbonPalette.white,
        interactive: CarbonPalette.blue60,
        highlight: CarbonPalette.blue20,
        overlay: CarbonPalette.overlay, // black @ 0.6
        toggleOff: CarbonPalette.gray50,
        shadow: const Color(0x4D000000), // rgba(0,0,0,0.3)
        supportError: CarbonPalette.red60,
        supportSuccess: CarbonPalette.green50,
        supportWarning: CarbonPalette.yellow30,
        supportInfo: CarbonPalette.blue70,
        supportErrorInverse: CarbonPalette.red50,
        supportSuccessInverse: CarbonPalette.green40,
        supportWarningInverse: CarbonPalette.yellow30,
        supportInfoInverse: CarbonPalette.blue50,
        supportCautionMinor: CarbonPalette.yellow30,
        supportCautionMajor: CarbonPalette.orange40,
        supportCautionUndefined: CarbonPalette.purple60,
      );
}
